name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.11.0
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run JUnit Tests
      run: API_KEY=${{ secrets.API_KEY }} mvn test

