name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.11.0
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run JUnit Tests
      run: mvn test
